export const fontFamily = {
  spacemono: ['spacemono'],
  manropebold: ['manropebold'],
  manropeextrabold: ['manropeextrabold'],
  manropeextralight: ['manropeextralight'],
  manropelight: ['manropelight'],
  manropemedium: ['manropemedium'],
  manroperegular: ['manroperegular'],
  manropesemibold: ['manropesemibold'],
};

export const colors = {
  DarkBlue: '#0B1C27',
  purpleBackground: '#234961',
  lightPurple: '#224257',
  darkGreen: '#22C524',
  unFocusedBorder: '#DBE3EB',
  error: '#FF4646',
  alertRed: '#F44848',
  pastelblue: '#086EA7',
  lightHeading: '#5C6C76',
  green: '#26B828',
  gold: '#E1A446',
  peach: '#FFF2DC',
  dark: '#000000',
  primaryGradient: '#FFF7EB',
  white: '#FFFFFF',
  appGradient: ['#FFF7EB', '#FFFFFF'],
  homeGradient: ['#FFFFFF', '#FFF5E5'],
  disabledColor: '#ccc',
  unfillBackground: '#EFE9E0',
  lightBlueBackground: '#ECF7FC',
  skyBlueBackground: '#F6FCFF',
  yellowBackground: '#EFE3CE',
  lightGoldBackground: '#FFF5E5',
  mediumGoldBackground: '#FDF5EB',
  darkGrayBackground: '#F5F5F5',
  goldenBackground: '#F5DEB7',
  grayText: '#8A8A8A',
  greenText: '#26B828',
  redText: '#D32F2F',
  lightGrayText: '#0B1C27B2',
  lightGrayBorder: '#D9E5EB',
  grayBorder: '#e5e5e5',
  lightWhiteBorder: '#f9f9f9',
  goldenBorder: '#E1A446',
  skyBlue: '#EBF5FC',
  lightBlackBorder: '#E1E1E1',
  progressBarBg: '#EBEBEB',
  progressBarRed: '#F44848',
  progressBarGray: '#707B82',
  lightGreenBorder: '#ADE7AE',
  lightGreenBg: '#F1FFF1',
  lightGrayBlackBorder: '#EAEAEA',
  lightSkyBlue: '#E0F0FA',
  lineBarGray: '#E2E2E2',
  lightWhiteText: 'rgba(255, 255, 255, 0.7)',
  blue: '#3BA6EB',
  lightBlue: '#F7FCFF',
  borderBlue: '#C0D6E0',
  hightlight: { r: 228, g: 175, b: 93 },
  darkHighlight: '#B09F84',
};

export const padding = {
  mainPadding: 'px-4',
};
